create table if not exists public.risk_assessments (
  id uuid primary key default gen_random_uuid(),
  employee_name text not null,
  age int,
  gender text,
  job_title text,
  experience_level text,
  years_of_service int,
  department text,
  task_type text,
  work_type text,
  location text,
  work_hours int,
  temperature numeric,
  humidity numeric,
  noise_level numeric,
  safety_training boolean,
  ppe_usage boolean,
  previous_incidents text[],
  equipment_condition text,
  weather_impact text,
  workload_level text,
  communication_quality text,
  supervisor_presence boolean,
  created_at timestamp with time zone default now()
);
